import { Config } from 'tailwindcss';

const colors = {
  text: {
    white: 'var(--text-white)',
    1: 'var(--text-1)',
    2: 'var(--text-2)',
    3: 'var(--text-3)',
    4: 'var(--text-4)',
    5: 'var(--text-5)',
    6: 'var(--text-6)',
    7: 'var(--text-7)',
    8: 'var(--text-8)',
    9: 'var(--text-9)',
    dark: 'var(--text-dark)',
  },
  background: {
    white: 'var(--background-white)',
    1: 'var(--background-1)',
    2: 'var(--background-2)',
    3: 'var(--background-3)',
    4: 'var(--background-4)',
    5: 'var(--background-5)',
    6: 'var(--background-6)',
    7: 'var(--background-7)',
    8: 'var(--background-8)',
    9: 'var(--background-9)',
    dark: 'var(--background-dark)',
  },
  primary: {
    white: 'var(--primary-white)',
    1: 'var(--primary-1)',
    2: 'var(--primary-2)',
    3: 'var(--primary-3)',
    4: 'var(--primary-4)',
    5: 'var(--primary-5)',
    6: 'var(--primary-6)',
    7: 'var(--primary-7)',
    8: 'var(--primary-8)',
    9: 'var(--primary-9)',
    dark: 'var(--primary-dark)',
  },
  secondary: {
    white: 'var(--secondary-white)',
    1: 'var(--secondary-1)',
    2: 'var(--secondary-2)',
    3: 'var(--secondary-3)',
    4: 'var(--secondary-4)',
    5: 'var(--secondary-5)',
    6: 'var(--secondary-6)',
    7: 'var(--secondary-7)',
    8: 'var(--secondary-8)',
    9: 'var(--secondary-9)',
    dark: 'var(--secondary-dark)',
  },
  accent: {
    white: 'var(--accent-white)',
    1: 'var(--accent-1)',
    2: 'var(--accent-2)',
    3: 'var(--accent-3)',
    4: 'var(--accent-4)',
    5: 'var(--accent-5)',
    6: 'var(--accent-6)',
    7: 'var(--accent-7)',
    8: 'var(--accent-8)',
    9: 'var(--accent-9)',
    dark: 'var(--accent-dark)',
  },
} satisfies Config['theme']['colors'];

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    colors,
    fontSize: {
      sm: '0.750rem',
      base: '1rem',
      xl: '1.333rem',
      '2xl': '1.777rem',
      '3xl': '2.369rem',
      '4xl': '3.158rem',
      '5xl': '4.210rem',
    },
    fontFamily: {
      heading: 'Akshar',
      body: 'Akshar',
    },
    fontWeight: {
      normal: '400',
      bold: '700',
    },
  },
} satisfies Config;
