import { NodeMaterials } from '@modules/renderer/engine/nodes/materials/NodeMaterialMap.js';
import { SpriteNodeMaterial } from '@modules/renderer/engine/nodes/materials/SpriteNodeMaterial.js';
import { PointsNodeMaterial } from '@modules/renderer/engine/nodes/materials/PointsNodeMaterial.js';
import { NodeMaterial } from '@modules/renderer/engine/nodes/materials/NodeMaterial.js';
import { MeshStandardNodeMaterial } from '@modules/renderer/engine/nodes/materials/MeshStandardNodeMaterial.js';
import { MeshSSSNodeMaterial } from '@modules/renderer/engine/nodes/materials/MeshSSSNodeMaterial.js';
import { MeshPhysicalNodeMaterial } from '@modules/renderer/engine/nodes/materials/MeshPhysicalNodeMaterial.js';
import { MeshPhongNodeMaterial } from '@modules/renderer/engine/nodes/materials/MeshPhongNodeMaterial.js';
import { MeshNormalNodeMaterial } from '@modules/renderer/engine/nodes/materials/MeshNormalNodeMaterial.js';
import { MeshLambertNodeMaterial } from '@modules/renderer/engine/nodes/materials/MeshLambertNodeMaterial.js';
import { MeshBasicNodeMaterial } from '@modules/renderer/engine/nodes/materials/MeshBasicNodeMaterial.js';
import { LineDashedNodeMaterial } from '@modules/renderer/engine/nodes/materials/LineDashedNodeMaterial.js';
import { LineBasicNodeMaterial } from '@modules/renderer/engine/nodes/materials/LineBasicNodeMaterial.js';
import { Line2NodeMaterial } from '@modules/renderer/engine/nodes/materials/Line2NodeMaterial.js';
import { InstancedPointsNodeMaterial } from '@modules/renderer/engine/nodes/materials/InstancedPointsNodeMaterial.js';

NodeMaterials.set('NodeMaterial', NodeMaterial);
NodeMaterials.set('SpriteNodeMaterial', SpriteNodeMaterial);
NodeMaterials.set('PointsNodeMaterial', PointsNodeMaterial);
NodeMaterials.set('MeshStandardNodeMaterial', MeshStandardNodeMaterial);
NodeMaterials.set('MeshSSSNodeMaterial', MeshSSSNodeMaterial);
NodeMaterials.set('MeshPhysicalNodeMaterial', MeshPhysicalNodeMaterial);
NodeMaterials.set('MeshPhongNodeMaterial', MeshPhongNodeMaterial);
NodeMaterials.set('MeshNormalNodeMaterial', MeshNormalNodeMaterial);
NodeMaterials.set('MeshLambertNodeMaterial', MeshLambertNodeMaterial);
NodeMaterials.set('MeshBasicNodeMaterial', MeshBasicNodeMaterial);
NodeMaterials.set('LineDashedNodeMaterial', LineDashedNodeMaterial);
NodeMaterials.set('LineBasicNodeMaterial', LineBasicNodeMaterial);
NodeMaterials.set('Line2NodeMaterial', Line2NodeMaterial);
NodeMaterials.set('InstancedPointsNodeMaterial', InstancedPointsNodeMaterial);
