import { Material } from '@modules/renderer/engine/entities/materials/Material.js';
import { NodeMaterial } from '@modules/renderer/engine/nodes/materials/NodeMaterial.js';
import { LineBasicMaterial } from '@modules/renderer/engine/entities/materials/LineBasicMaterial.js';
import { LineBasicNodeMaterial } from '@modules/renderer/engine/nodes/materials/LineBasicNodeMaterial.js';
import { LineDashedMaterial } from '@modules/renderer/engine/entities/materials/LineDashedMaterial.js';
import { LineDashedNodeMaterial } from '@modules/renderer/engine/nodes/materials/LineDashedNodeMaterial.js';
import { MeshBasicMaterial } from '@modules/renderer/engine/entities/materials/MeshBasicMaterial.js';
import { MeshBasicNodeMaterial } from '@modules/renderer/engine/nodes/materials/MeshBasicNodeMaterial.js';
import { MeshLambertMaterial } from '@modules/renderer/engine/entities/materials/MeshLambertMaterial.js';
import { MeshLambertNodeMaterial } from '@modules/renderer/engine/nodes/materials/MeshLambertNodeMaterial.js';
import { MeshMatcapMaterial } from '@modules/renderer/engine/entities/materials/MeshMatcapMaterial.js';
import { MeshMatcapNodeMaterial } from '@modules/renderer/engine/nodes/materials/MeshMatcapNodeMaterial.js';
import { MeshNormalMaterial } from '@modules/renderer/engine/entities/materials/MeshNormalMaterial.js';
import { MeshNormalNodeMaterial } from '@modules/renderer/engine/nodes/materials/MeshNormalNodeMaterial.js';
import { MeshPhongMaterial } from '@modules/renderer/engine/entities/materials/MeshPhongMaterial.js';
import { MeshPhongNodeMaterial } from '@modules/renderer/engine/nodes/materials/MeshPhongNodeMaterial.js';
import { MeshPhysicalMaterial } from '@modules/renderer/engine/entities/materials/MeshPhysicalMaterial.js';
import { MeshPhysicalNodeMaterial } from '@modules/renderer/engine/nodes/materials/MeshPhysicalNodeMaterial.js';
import { MeshStandardMaterial } from '@modules/renderer/engine/entities/materials/MeshStandardMaterial.js';
import { MeshStandardNodeMaterial } from '@modules/renderer/engine/nodes/materials/MeshStandardNodeMaterial.js';
import { MeshToonMaterial } from '@modules/renderer/engine/entities/materials/MeshToonMaterial.js';
import { MeshToonNodeMaterial } from '@modules/renderer/engine/nodes/materials/MeshToonNodeMaterial.js';
import { PointsMaterial } from '@modules/renderer/engine/entities/materials/PointsMaterial.js';
import { PointsNodeMaterial } from '@modules/renderer/engine/nodes/materials/PointsNodeMaterial.js';
import { ShadowMaterial } from '@modules/renderer/engine/entities/materials/ShadowMaterial.js';
import { ShadowNodeMaterial } from '@modules/renderer/engine/nodes/materials/ShadowNodeMaterial.js';
import { SpriteMaterial } from '@modules/renderer/engine/entities/materials/SpriteMaterial.js';
import { SpriteNodeMaterial } from '@modules/renderer/engine/nodes/materials/SpriteNodeMaterial.js';

NodeMaterial.Mapping.set(Material, NodeMaterial);
NodeMaterial.Mapping.set(LineBasicMaterial, LineBasicNodeMaterial);
NodeMaterial.Mapping.set(LineDashedMaterial, LineDashedNodeMaterial);
NodeMaterial.Mapping.set(MeshBasicMaterial, MeshBasicNodeMaterial);
NodeMaterial.Mapping.set(MeshLambertMaterial, MeshLambertNodeMaterial);
NodeMaterial.Mapping.set(MeshMatcapMaterial, MeshMatcapNodeMaterial);
NodeMaterial.Mapping.set(MeshNormalMaterial, MeshNormalNodeMaterial);
NodeMaterial.Mapping.set(MeshPhongMaterial, MeshPhongNodeMaterial);
NodeMaterial.Mapping.set(MeshPhysicalMaterial, MeshPhysicalNodeMaterial);
NodeMaterial.Mapping.set(MeshStandardMaterial, MeshStandardNodeMaterial);
NodeMaterial.Mapping.set(MeshToonMaterial, MeshToonNodeMaterial);
NodeMaterial.Mapping.set(PointsMaterial, PointsNodeMaterial);
NodeMaterial.Mapping.set(ShadowMaterial, ShadowNodeMaterial);
NodeMaterial.Mapping.set(SpriteMaterial, SpriteNodeMaterial);
