import type { Config } from "npm:tailwindcss@^3.4.11";

const colors = {
  text: {
    white: "rgb(var(--text-white) / <alpha-value>)",
    1: "rgb(var(--text-1) / <alpha-value>)",
    2: "rgb(var(--text-2) / <alpha-value>)",
    3: "rgb(var(--text-3) / <alpha-value>)",
    4: "rgb(var(--text-4) / <alpha-value>)",
    5: "rgb(var(--text-5) / <alpha-value>)",
    6: "rgb(var(--text-6) / <alpha-value>)",
    7: "rgb(var(--text-7) / <alpha-value>)",
    8: "rgb(var(--text-8) / <alpha-value>)",
    9: "rgb(var(--text-9) / <alpha-value>)",
    dark: "rgb(var(--text-dark) / <alpha-value>)",
  },
  background: {
    white: "rgb(var(--background-white) / <alpha-value>)",
    1: "rgb(var(--background-1) / <alpha-value>)",
    2: "rgb(var(--background-2) / <alpha-value>)",
    3: "rgb(var(--background-3) / <alpha-value>)",
    4: "rgb(var(--background-4) / <alpha-value>)",
    5: "rgb(var(--background-5) / <alpha-value>)",
    6: "rgb(var(--background-6) / <alpha-value>)",
    7: "rgb(var(--background-7) / <alpha-value>)",
    8: "rgb(var(--background-8) / <alpha-value>)",
    9: "rgb(var(--background-9) / <alpha-value>)",
    dark: "rgb(var(--background-dark) / <alpha-value>)",
  },
  primary: {
    white: "rgb(var(--primary-white) / <alpha-value>)",
    1: "rgb(var(--primary-1) / <alpha-value>)",
    2: "rgb(var(--primary-2) / <alpha-value>)",
    3: "rgb(var(--primary-3) / <alpha-value>)",
    4: "rgb(var(--primary-4) / <alpha-value>)",
    5: "rgb(var(--primary-5) / <alpha-value>)",
    6: "rgb(var(--primary-6) / <alpha-value>)",
    7: "rgb(var(--primary-7) / <alpha-value>)",
    8: "rgb(var(--primary-8) / <alpha-value>)",
    9: "rgb(var(--primary-9) / <alpha-value>)",
    dark: "rgb(var(--primary-dark) / <alpha-value>)",
  },
  secondary: {
    white: "rgb(var(--secondary-white) / <alpha-value>)",
    1: "rgb(var(--secondary-1) / <alpha-value>)",
    2: "rgb(var(--secondary-2) / <alpha-value>)",
    3: "rgb(var(--secondary-3) / <alpha-value>)",
    4: "rgb(var(--secondary-4) / <alpha-value>)",
    5: "rgb(var(--secondary-5) / <alpha-value>)",
    6: "rgb(var(--secondary-6) / <alpha-value>)",
    7: "rgb(var(--secondary-7) / <alpha-value>)",
    8: "rgb(var(--secondary-8) / <alpha-value>)",
    9: "rgb(var(--secondary-9) / <alpha-value>)",
    dark: "rgb(var(--secondary-dark) / <alpha-value>)",
  },
  accent: {
    white: "rgb(var(--accent-white) / <alpha-value>)",
    1: "rgb(var(--accent-1) / <alpha-value>)",
    2: "rgb(var(--accent-2) / <alpha-value>)",
    3: "rgb(var(--accent-3) / <alpha-value>)",
    4: "rgb(var(--accent-4) / <alpha-value>)",
    5: "rgb(var(--accent-5) / <alpha-value>)",
    6: "rgb(var(--accent-6) / <alpha-value>)",
    7: "rgb(var(--accent-7) / <alpha-value>)",
    8: "rgb(var(--accent-8) / <alpha-value>)",
    9: "rgb(var(--accent-9) / <alpha-value>)",
    dark: "rgb(var(--accent-dark) / <alpha-value>)",
  },
  golden: {
    white: "rgb(var(--golden-white) / <alpha-value>)",
    1: "rgb(var(--golden-1) / <alpha-value>)",
    2: "rgb(var(--golden-2) / <alpha-value>)",
    3: "rgb(var(--golden-3) / <alpha-value>)",
    4: "rgb(var(--golden-4) / <alpha-value>)",
    5: "rgb(var(--golden-5) / <alpha-value>)",
    6: "rgb(var(--golden-6) / <alpha-value>)",
    7: "rgb(var(--golden-7) / <alpha-value>)",
    8: "rgb(var(--golden-8) / <alpha-value>)",
    9: "rgb(var(--golden-9) / <alpha-value>)",
    dark: "rgb(var(--golden-dark) / <alpha-value>)",
  },
  transparent: "transparent",
  current: "currentColor",
} satisfies Config["theme"]["colors"];

export const config = {
  darkMode: "class",
  theme: {
    colors,
    fontSize: {
      xs: "0.666rem",
      sm: "0.750rem",
      base: "1rem",
      lg: "1.333rem",
      xl: "1.500rem",
      "2xl": "1.777rem",
      "3xl": "2.369rem",
      "4xl": "3.158rem",
      "5xl": "4.210rem",
    },
    fontFamily: {
      heading: "Akshar",
      body: "Akshar",
    },
    fontWeight: {
      normal: "400",
      bold: "700",
    },
  },
} satisfies Config;
