export const Example = {
  Compute: {
    Audio: 'compute_audio',
    Particles: {
      Particle: 'compute_particles',
      Rain: 'compute_particles_rain',
      Snow: 'compute_particles_snow',
    },
    Points: 'compute_points',
    Textures: {
      Texture: 'compute_texture',
      PingPong: 'compute_texture_pingpong',
    },
  },
  Backdrop: 'backdrop',
  BackdropArea: 'backdrop_area',
  BackdropWater: 'backdrop_water',
  CameraLogarithmicDepthBuffer: 'camera_logarithmicdepthbuffer',
  Clearcoat: 'clearcoat',
  Clipping: 'clipping',
  CubemapAdjustments: 'cubemap_adjustments',
  CubemapDynamic: 'cubemap_dynamic',
  CubemapMix: 'cubemap_mix',
  CustomFog: 'custom_fog',
  CustomFogBackground: 'custom_fog_background',
  DepthTexture: 'depth_texture',
  Equirectangular: 'equirectangular',
  InstanceMesh: 'instance_mesh',
  InstancePoints: 'instance_points',
  InstanceUniform: 'instance_uniform',
  LightsCustom: 'lights_custom',
  LightsIesSpotlight: 'lights_ies_spotlight',
  LightsPhong: 'lights_phong',
  LightsSelective: 'lights_selective',
  LinesFat: 'lines_fat',
  LoaderGltfSheen: 'loader_gltf_sheen',
  Materials: 'materials',
  MaterialsTextureAnisotropy: 'materials_texture_anisotropy',
  MaterialsTexturePartialUpdate: 'materials_texture_partialupdate',
  MaterialsVideo: 'materials_video',
  Mirror: 'mirror',
  MorphTargets: 'morphtargets',
  MorphTargetsFace: 'morphtargets_face',
  MultipleRenderTargets: 'multiple_rendertargets',
  MultiSampledRenderBuffers: 'multisampled_renderbuffers',
  Occlusion: 'occlusion',
  ParallaxUv: 'parallax_uv',
  Particles: 'particles',
  PmRemCubemap: 'pmrem_cubemap',
  PmRemEquirectangular: 'pmrem_equirectangular',
  PmRemScene: 'pmrem_scene',
  Portal: 'portal',
  PostprocessingAfterimage: 'postprocessing_afterimage',
  PostprocessingAnamorphic: 'postprocessing_anamorphic',
  Reflection: 'reflection',
  Rtt: 'rtt',
  Sandbox: 'sandbox',
  ShaderToy: 'shadertoy',
  ShadowMap: 'shadowmap',
  Skinning: 'skinning',
  SkinningInstancing: 'skinning_instancing',
  SkinningPoints: 'skinning_points',
  Sprites: 'sprites',
  StorageBuffer: 'storage_buffer',
  Textures2dArray: 'textures_2d-array',
  TslEditor: 'tsl_editor',
  TslTranspiler: 'tsl_transpiler',
  VideoPanorama: 'video_panorama',
  Loaders: {
    Stl: 'loader_stl',
    Tiff: 'loader_tiff',
    Ttf: 'ttf_loader',
    Obj: 'loader_obj',
    ObjMtl: 'loader_obj_mtl',
    Gltfs: {
      Gltf: 'loader_gltf',
      Ktx2: 'loader_gltf_ktx2',
      Draco: 'loader_gltf_draco',
      Iridescence: 'loader_gltf_iridescence',
      Sheen: 'loader_gltf_sheen',
    },
  },
  Physics: {
    Ammo: 'physics_ammo',
  },
};

export type ExampleName = keyof typeof Example;
