import { Material } from '../../entities/materials/Material.js';
import { NodeMaterial } from '../../nodes/materials/NodeMaterial.js';
import { LineBasicMaterial } from '../../entities/materials/LineBasicMaterial.js';
import { LineBasicNodeMaterial } from '../../nodes/materials/LineBasicNodeMaterial.js';
import { LineDashedMaterial } from '../../entities/materials/LineDashedMaterial.js';
import { LineDashedNodeMaterial } from '../../nodes/materials/LineDashedNodeMaterial.js';
import { MeshBasicMaterial } from '../../entities/materials/MeshBasicMaterial.js';
import { MeshBasicNodeMaterial } from '../../nodes/materials/MeshBasicNodeMaterial.js';
import { MeshLambertMaterial } from '../../entities/materials/MeshLambertMaterial.js';
import { MeshLambertNodeMaterial } from '../../nodes/materials/MeshLambertNodeMaterial.js';
import { MeshMatcapMaterial } from '../../entities/materials/MeshMatcapMaterial.js';
import { MeshMatcapNodeMaterial } from '../../nodes/materials/MeshMatcapNodeMaterial.js';
import { MeshNormalMaterial } from '../../entities/materials/MeshNormalMaterial.js';
import { MeshNormalNodeMaterial } from '../../nodes/materials/MeshNormalNodeMaterial.js';
import { MeshPhongMaterial } from '../../entities/materials/MeshPhongMaterial.js';
import { MeshPhongNodeMaterial } from '../../nodes/materials/MeshPhongNodeMaterial.js';
import { MeshPhysicalMaterial } from '../../entities/materials/MeshPhysicalMaterial.js';
import { MeshPhysicalNodeMaterial } from '../../nodes/materials/MeshPhysicalNodeMaterial.js';
import { MeshStandardMaterial } from '../../entities/materials/MeshStandardMaterial.js';
import { MeshStandardNodeMaterial } from '../../nodes/materials/MeshStandardNodeMaterial.js';
import { MeshToonMaterial } from '../../entities/materials/MeshToonMaterial.js';
import { MeshToonNodeMaterial } from '../../nodes/materials/MeshToonNodeMaterial.js';
import { PointsMaterial } from '../../entities/materials/PointsMaterial.js';
import { PointsNodeMaterial } from '../../nodes/materials/PointsNodeMaterial.js';
import { ShadowMaterial } from '../../entities/materials/ShadowMaterial.js';
import { ShadowNodeMaterial } from '../../nodes/materials/ShadowNodeMaterial.js';
import { SpriteMaterial } from '../../entities/materials/SpriteMaterial.js';
import { SpriteNodeMaterial } from '../../nodes/materials/SpriteNodeMaterial.js';

NodeMaterial.Mapping.set(Material, NodeMaterial);
NodeMaterial.Mapping.set(LineBasicMaterial, LineBasicNodeMaterial);
NodeMaterial.Mapping.set(LineDashedMaterial, LineDashedNodeMaterial);
NodeMaterial.Mapping.set(MeshBasicMaterial, MeshBasicNodeMaterial);
NodeMaterial.Mapping.set(MeshLambertMaterial, MeshLambertNodeMaterial);
NodeMaterial.Mapping.set(MeshMatcapMaterial, MeshMatcapNodeMaterial);
NodeMaterial.Mapping.set(MeshNormalMaterial, MeshNormalNodeMaterial);
NodeMaterial.Mapping.set(MeshPhongMaterial, MeshPhongNodeMaterial);
NodeMaterial.Mapping.set(MeshPhysicalMaterial, MeshPhysicalNodeMaterial);
NodeMaterial.Mapping.set(MeshStandardMaterial, MeshStandardNodeMaterial);
NodeMaterial.Mapping.set(MeshToonMaterial, MeshToonNodeMaterial);
NodeMaterial.Mapping.set(PointsMaterial, PointsNodeMaterial);
NodeMaterial.Mapping.set(ShadowMaterial, ShadowNodeMaterial);
NodeMaterial.Mapping.set(SpriteMaterial, SpriteNodeMaterial);
